version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./project:/var/www/symfony
    working_dir: /var/www/symfony
    environment:
      - APP_ENV=dev
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Nginx Service
  nginx:
    image: nginx:alpine
    volumes:
      - ./my_project:/var/www/symfony:ro,cached
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php

volumes:
  mysql-data: