version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/symfony
    working_dir: /var/www/symfony
    environment:
      - APP_ENV=dev
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Nginx Service
  nginx:
    image: nginx:alpine
    volumes:
      - ./my_project:/var/www/symfony:ro,cached
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  mysql-data:
